---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: postgresql restart
    systemd:
      name: postgresql
      state: restarted

  - name: get service facts
    ansible.builtin.service_facts: true

  - name: dump postgresql service
    ansible.builtin.debug:
      var: ansible_facts.services["postgresql.service"]

  - name: Assert postgresql.service is enabled
    ansible.builtin.assert:
      that: ansible_facts.services["postgresql.service"]["status"] == "enabled"
...
