---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Postgresql restart
    ansible.builtin.systemd_service:
      name: postgresql
      state: restarted

  - name: Get Service Status
    ansible.builtin.systemd_service:
      name: "postgresql.service"
    register: pg_service_status

  - name: Dump postgresql service
    ansible.builtin.debug:
      var: pg_service_status

  - name: Assert postgresql.service is enabled
    ansible.builtin.assert:
      that: pg_service_status.status.ActiveState == "active"

...
