---
- name: Converge clientsonly
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  vars:
    postgresql_listen: "0.0.0.0"
    postgresql_clients_only: true
  tasks:
  - name: Include andrelohmann.postgresql
    ansible.builtin.include_role:
      name: "andrelohmann.postgresql"
...
