---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: false
  tasks:

  - name: Run pg_dump --version
    ansible.builtin.shell: pg_dump --version
    args:
      executable: /bin/bash
    register: return_pg_dump
    changed_when: false

  - name: Dump return_pg_dump
    ansible.builtin.debug:
      var: return_pg_dump

  - name: Run psql --version
    ansible.builtin.shell: psql --version
    args:
      executable: /bin/bash
    register: return_psql
    changed_when: false

  - name: Dump return_psql
    ansible.builtin.debug:
      var: return_psql

  - name: Assert pg_dump and psql to return Version 17.*
    ansible.builtin.assert:
      that:
      - return_pg_dump.rc == 0
      - return_pg_dump.stdout is search('pg_dump')
      - return_pg_dump.stdout is search('17.')
      - return_psql.rc == 0
      - return_psql.stdout is search('psql')
      - return_psql.stdout is search('17.')

...
